# Here you can specify default options for TinyMCE across all controllers
#
theme: advanced
width: 520
height: 300
relative_urls: false
theme_advanced_buttons1: "bold,italic,underline,strikethrough,|,bullist,numlist,|,link,unlink,image,media,|,removeformat,pastetext,pasteword,|,selectall,undo,redo,|,upload,code"
theme_advanced_buttons2: ""
theme_advanced_buttons3: ""
plugins:
 - table
 - fullscreen
 - paste
 - upload
 - media
